name: CI
permissions:
  contents: write
  id-token: write
'on':
  push:
    tags:
      - 'v*'
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: windows-latest
            publish: yarn run publish
          - host: ubuntu-latest
            publish: yarn run publish
          - host: macos-latest
            publish: yarn run publish
    name: stable - ${{ matrix.settings.host }} - node@20
    runs-on: ${{ matrix.settings.host }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - name: Install dependencies
        run: yarn install
      - name: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ${{ matrix.settings.publish }}
  